### ISSUE TITLE
Cleaning up old drafts fails because of record versioning information

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/invenio-drafts-resources#178]
Package version (if known): 0.14.6

## Describe the bug
The task `cleanup_drafts` sometimes fails because of violated foreign key constraints in the record versioning table.  
Every now and then, we would encounter a stack trace similar to the following (`invenio-cli run`):

```
[2021-12-16 11:04:27,185: ERROR/ForkPoolWorker-17] Task invenio_drafts_resources.services.records.tasks.cleanup_drafts[dc1608d3-4e06-4e1d-880f-8725a6ef72bb] raised unexpected: IntegrityError('(psycopg2.errors.ForeignKeyViolation) update or delete on table "rdm_drafts_metadata" violates foreign key constraint "fk_rdm_versions_state_next_draft_id_rdm_drafts_metadata" on table "rdm_versions_state"\nDETAIL:  Key (id)=(b09b67de-d822-474d-acb5-cf92bd67a802) is still referenced from table "rdm_versions_state".\n')
Traceback (most recent call last):
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: update or delete on table "rdm_drafts_metadata" violates foreign key constraint "fk_rdm_versions_state_next_draft_id_rdm_drafts_metadata" on table "rdm_versions_state"
DETAIL:  Key (id)=(b09b67de-d822-474d-acb5-cf92bd67a802) is still referenced from table "rdm_versions_state".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/flask_celeryext/app.py", line 84, in __call__
    return Task.__call__(self, *args, **kwargs)
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/invenio_drafts_resources/services/records/tasks.py", line 26, in cleanup_drafts
    service.cleanup_drafts(timedelta_param)
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/invenio_records_resources/services/uow.py", line 292, in inner
    res = f(self, *args, **kwargs)
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/invenio_drafts_resources/services/records/service.py", line 525, in cleanup_drafts
    self.draft_cls.cleanup_drafts(timedelta)
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/invenio_drafts_resources/records/api.py", line 240, in cleanup_drafts
    draft_model.query.filter(
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3926, in delete
    delete_op.exec_()
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1697, in exec_
    self._do_exec()
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1930, in _do_exec
    self._execute_stmt(delete_stmt)
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1702, in _execute_stmt
    self.result = self.query._execute_crud(stmt, self.mapper)
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3568, in _execute_crud
    return conn.execute(stmt, self._params)
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/mmoser/.local/share/virtualenvs/tu-data-hHy_bWtj/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table "rdm_drafts_metadata" violates foreign key constraint "fk_rdm_versions_state_next_draft_id_rdm_drafts_metadata" on table "rdm_versions_state"
DETAIL:  Key (id)=(b09b67de-d822-474d-acb5-cf92bd67a802) is still referenced from table "rdm_versions_state".

[SQL: DELETE FROM rdm_drafts_metadata WHERE (rdm_drafts_metadata.json IS NULL) = true AND rdm_drafts_metadata.updated < %(updated_1)s]
[parameters: {'updated_1': datetime.datetime(2021, 12, 16, 9, 4, 27, 158183)}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

It looks like the record versioning information for the drafts in question has to be cleared as well, before being able to hard-delete the drafts.

**Comment by apirogov** [comment]
I seem to have the same problem, and once it starts, for me the stacktrace comes exactly once per hour.

**Comment by max-moser** [comment]
note: the PRs on records-resources and requests don't have anything to do with this issue, i just copy-pasted the wrong link...
